### PR TITLE
Update .travis.yml for macos, correct CMake min version, abstract precision

### PR DESCRIPTION
**Pull request by scivision**
Note that specification of REAL precision at Cmake doesn't appear to be working (before or now).

### CODE REVIEW

**Comment by milancurcic** [comment]
Michael, thank you for the PR!

You're right, the REAL precision switch does nothing for now, not implemented in code yet.

Are delayed Travis builds on OS X common?

**Comment by milancurcic** [comment]
> In your book do you mention for Windows the Cygwin and Windows Subsystem for Linux options?

Windows Subsystem for Linux yes, Cygwin no and no plans.

**Comment by scivision** [comment]
Yes [delayed osx builds](https://www.scivision.co/travis-ci-osx-build-speed/) are common.

**Comment by scivision** [comment]
OK sticking to WSL vs. Cygwin sounds like a good plan

**Pull request merged**
